import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import LayoutRapper from "@/app/(public)/components/LayoutRapper"
import "./globals.css";

const poppins = Poppins({
  weight:["100","200","300","400","600","700","800","900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Financial Advisory System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-gray-50/95 max-w-[1680px] mx-auto`}
      >
        <LayoutRapper>{children}</LayoutRapper>
      </body>
    </html>
  );
}
