import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import LayoutRapper from '@/app/(public)/components/LayoutRapper';
import './globals.css';
import StoreProvider from './StoreProvider';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Financial Advisory System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-[#E2F3F9] max-w-[1680px] mx-auto`}>
        <StoreProvider>
          <LayoutRapper>{children}</LayoutRapper>
        </StoreProvider>
      </body>
    </html>
  );
}
