import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import LayoutRapper from '@/app/(public)/components/LayoutRapper';
import './globals.css';
import StoreProvider from './StoreProvider';
import { ThemeProvider } from '@/lib/themes/theme-provider';

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Financial Advisory System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} antialiased !bg-[#E2F3F9] !text-[#182641] dark:!text-white max-w-[1680px] mx-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <LayoutRapper>{children}</LayoutRapper>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
